### ISSUE TITLE
It crashing game after CE injecting

### ISSUE THREAD

**Issue by HexPa5** [paysonism/UnrealDumper#1]
Hey, I try to test on Gotham Knights (UE4) and Batman Arkham Knight (UE3) games and it not working.
It was injected to the game process with Cheat Engine 64 Bit version, help!

**Comment by paysonism** [comment]
Let me know if it works bc if it doesn't i'll add updating the sigs in this to my to-do list. And if you update the sigs or get it working please make a pull request ❤️

**Comment by HexPa5** [comment]
Okey so I used your injector, the unrealdumper name was renamed and it was successfully loaded. 
Unfortunately arkham knight game store a lot of hardcoded data of some offsets, it would be great if you update signs.
By the way, we have available UPK Explorer tool released on Nexusmods, it support a lot of UE3 games classes, including early development of UE2 games. Maybe it's a clue for finding Window class name hopefully :)

**Comment by paysonism** [comment]
The window class name might be the same since its and Unreal Engine process. Just look around for the Unreal Engine class name for the version of Unreal Engine your game is running. I will try to find the new sigs and update this soon though. Good luck on your project! ❤️

**Comment by HexPa5** [comment]
Well Engine.upk was open and I search for any version string name and found as unsupported class called "EngineVersion" as StrProperty type and other one with the same name as IntProperty.
I can't view that or even export as cooked binary because this tool don't support everything. All I know it's very modified Unreal Engine 3 Batman game

**Comment by HexPa5** [comment]
![screenshot (68)](https://github.com/paysonism/UnrealDumper/assets/58123856/3a0f34e9-6787-4538-8676-ab17b1669dd1)
Okey just loaded other tool and it say engine version is 10246 like on screenshot
